[build]
builder = "DOCKERFILE"
dockerfilePath = "contrib/container/Dockerfile"

[deploy]
startCommand = "gunicorn --chdir /home/inventree/src/backend/InvenTree InvenTree.wsgi:application -b 0.0.0.0:$PORT --workers 4 --threads 2"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
APP_HOME = "/home/inventree"
DEBUG = "False"

[deploy]
startCommand = "echo $PORT && gunicorn --chdir /home/inventree/src/backend/InvenTree InvenTree.wsgi:application -b 0.0.0.0:$PORT --workers 4 --threads 2"