[build]
builder = "DOCKERFILE"
dockerfilePath = "contrib/container/Dockerfile"

[build.commands]
pre = ["python /home/inventree/src/backend/InvenTree/manage.py migrate", "python /home/inventree/src/backend/InvenTree/manage.py collectstatic --noinput"]

[deploy]
startCommand = "gunicorn --chdir /home/inventree/src/backend/InvenTree InvenTree.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
APP_HOME = "/home/inventree"
SECRET_KEY = "your-django-secret-key"
DEBUG = "False"
INVENTREE_STATIC_ROOT = "/home/inventree/static"
INVENTREE_MEDIA_ROOT = "/home/inventree/media"