[build]
builder = "DOCKERFILE"
dockerfilePath = "contrib/container/Dockerfile"

[deploy]
startCommand = "gunicorn --chdir /inventree/src/backend/InvenTree -c /inventree/src/backend/InvenTree/gunicorn.conf.py InvenTree.wsgi:application -b 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
APP_HOME = "/inventree"