[build]
builder = "DOCKERFILE"
RAILWAY_DOCKERFILE_PATH = "/InvenTree/contrib/container/Dockerfile"  

[deploy]
startCommand = "sh", "-c", "exec gunicorn -c ./gunicorn.conf.py InvenTree.wsgi -b 0.0.0.0:8000 --chdir ${INVENTREE_BACKEND_DIR}/InvenTree"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRet
ries = 10