version: '3.8'
services:
  inventree-cache:
    image: redis:7-alpine
    container_name: inventree-cache
    env_file:
      - .env
    expose:
      - ${INVENTREE_CACHE_PORT:-6379}
    restart: always

  inventree-server:
    image: inventree/inventree:${INVENTREE_TAG:-stable}
    container_name: inventree-server
    expose:
      - 8000
    depends_on:
      - inventree-cache
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${INVENTREE_DB_USER}:${INVENTREE_DB_PASSWORD}@${INVENTREE_DB_HOST}:${INVENTREE_DB_PORT}/${INVENTREE_DB_NAME}?sslmode=require
    volumes:
      - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
    restart: unless-stopped

  inventree-worker:
    image: inventree/inventree:${INVENTREE_TAG:-stable}
    container_name: inventree-worker
    command: invoke worker
    depends_on:
      - inventree-server
      - inventree-cache
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${INVENTREE_DB_USER}:${INVENTREE_DB_PASSWORD}@${INVENTREE_DB_HOST}:${INVENTREE_DB_PORT}/${INVENTREE_DB_NAME}?sslmode=require
    volumes:
      - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
    restart: unless-stopped

  inventree-proxy:
    container_name: inventree-proxy
    image: caddy:alpine
    restart: always
    depends_on:
      - inventree-server
    ports:
      - ${INVENTREE_WEB_PORT:-80}:80
      - 443:443
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
      - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
      - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
      - ${INVENTREE_EXT_VOLUME}:/var/log:z
      - ${INVENTREE_EXT_VOLUME}:/data:z
      - ${INVENTREE_EXT_VOLUME}:/config:z